### ISSUE TITLE
NoMethodError: undefined method `new' for Sidekiq::Worker:Module

### ISSUE THREAD

**Issue by damuz91** [russ/sidekiq-history#20]
Just installed sidekiq-history but doing a quick test gets me the following error while performing any Job execution:

```
2022-02-01T21:20:45.815Z pid=34321 tid=y8d INFO: Booted Rails 5.2.6 application in development environment
2022-02-01T21:20:45.815Z pid=34321 tid=y8d INFO: Running in ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-darwin19]
2022-02-01T21:20:45.815Z pid=34321 tid=y8d INFO: See LICENSE and the LGPL-3.0 for licensing details.
2022-02-01T21:20:45.815Z pid=34321 tid=y8d INFO: Upgrade to Sidekiq Pro for more features and support: https://sidekiq.org
2022-02-01T21:20:45.821Z pid=34321 tid=y8d INFO: Starting processing, hit Ctrl-C to stop
2022-02-01T21:20:45.895Z pid=34321 tid=106h class=PostRectificationJob jid=935c54f0f8d0f52dc3a8a371 INFO: start
/Users/damuz91/.rvm/gems/ruby-2.7.0/gems/activerecord-5.2.6/lib/active_record/type.rb:27: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/Users/damuz91/.rvm/gems/ruby-2.7.0/gems/activerecord-5.2.6/lib/active_record/type/adapter_specific_registry.rb:9: warning: The called method `add_modifier' is defined here
2022-02-01T21:20:46.052Z pid=34321 tid=106h class=PostRectificationJob jid=935c54f0f8d0f52dc3a8a371 elapsed=0.157 INFO: fail
2022-02-01T21:20:46.052Z pid=34321 tid=106h WARN: {"context":"Job raised exception","job":{"retry":true,"queue":"rectification","class":"ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper","wrapped":"PostRectificationJob","args":[{"job_class":"PostRectificationJob","job_id":"2b8aaa7c-99bb-45d8-b98c-c917de6b7e51","provider_job_id":null,"queue_name":"rectification","priority":null,"arguments":[9511407],"executions":0,"locale":"en"}],"jid":"935c54f0f8d0f52dc3a8a371","created_at":1643750407.313024,"enqueued_at":1643750407.313397},"jobstr":"{\"retry\":true,\"queue\":\"rectification\",\"class\":\"ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper\",\"wrapped\":\"PostRectificationJob\",\"args\":[{\"job_class\":\"PostRectificationJob\",\"job_id\":\"2b8aaa7c-99bb-45d8-b98c-c917de6b7e51\",\"provider_job_id\":null,\"queue_name\":\"rectification\",\"priority\":null,\"arguments\":[9511407],\"executions\":0,\"locale\":\"en\"}],\"jid\":\"935c54f0f8d0f52dc3a8a371\",\"created_at\":1643750407.313024,\"enqueued_at\":1643750407.313397}"}
2022-02-01T21:20:46.052Z pid=34321 tid=106h WARN: NoMethodError: undefined method `new' for Sidekiq::Worker:Module
2022-02-01T21:20:46.052Z pid=34321 tid=106h WARN: /Users/damuz91/.rvm/gems/ruby-2.7.0/gems/sidekiq-history-0.0.11/lib/sidekiq/history/middleware.rb:14:in `call'
/Users/damuz91/.rvm/gems/ruby-2.7.0/gems/sidekiq-6.3.1/lib/sidekiq/middleware/chain.rb:140:in `block in invoke'
/Users/damuz91/.rvm/gems/ruby-2.7.0/gems/sidekiq-batch-0.1.6/lib/sidekiq/batch/middleware.rb:30:in `call'
/Users/damuz91/.rvm/gems/ruby-2.7.0/gems/sidekiq-6.3.1/lib/sidekiq/middleware/chain.rb:140:in `block in invoke'
/Users/damuz91/.rvm/gems/ruby-2.7.0/gems/sidekiq-6.3.1/lib/sidekiq/middleware/chain.rb:143:in `invoke'
/Users/damuz91/.rvm/gems/ruby-2.7.0/gems/sidekiq-6.3.1/lib/sidekiq/processor.rb:163:in `block in process'
/Users/damuz91/.rvm/gems/ruby-2.7.0/gems/sidekiq-6.3.1/lib/sidekiq/processor.rb:136:in `block (6 levels) in dispatch'
/Users/damuz91/.rvm/gems/ruby-2.7.0/gems/sidekiq-6.3.1/lib/sidekiq/job_retry.rb:112:in `local'
/Users/damuz91/.rvm/gems/ruby-2.7.0/gems/sidekiq-6.3.1/lib/sidekiq/processor.rb:135:in `block (5 levels) in dispatch'
/Users/damuz91/.rvm/gems/ruby-2.7.0/gems/sidekiq-6.3.1/lib/sidekiq/rails.rb:14:in `block in call'
/Users/damuz91/.rvm/gems/ruby-2.7.0/gems/activesupport-5.2.6/lib/active_support/execution_wrapper.rb:87:in `wrap'
/Users/damuz91/.rvm/gems/ruby-2.7.0/gems/activesupport-5.2.6/lib/active_support/reloader.rb:73:in `block in wrap'
/Users/damuz91/.rvm/gems/ruby-2.7.0/gems/activesupport-5.2.6/lib/active_support/execution_wrapper.rb:87:in `wrap'
/Users/damuz91/.rvm/gems/ruby-2.7.0/gems/activesupport-5.2.6/lib/active_support/reloader.rb:72:in `wrap'
/Users/damuz91/.rvm/gems/ruby-2.7.0/gems/sidekiq-6.3.1/lib/sidekiq/rails.rb:13:in `call'
/Users/damuz91/.rvm/gems/ruby-2.7.0/gems/sidekiq-6.3.1/lib/sidekiq/processor.rb:131:in `block (4 levels) in dispatch'
/Users/damuz91/.rvm/gems/ruby-2.7.0/gems/sidekiq-6.3.1/lib/sidekiq/processor.rb:257:in `stats'
/Users/damuz91/.rvm/gems/ruby-2.7.0/gems/sidekiq-6.3.1/lib/sidekiq/processor.rb:126:in `block (3 levels) in dispatch'
/Users/damuz91/.rvm/gems/ruby-2.7.0/gems/sidekiq-6.3.1/lib/sidekiq/job_logger.rb:13:in `call'
/Users/damuz91/.rvm/gems/ruby-2.7.0/gems/sidekiq-6.3.1/lib/sidekiq/processor.rb:125:in `block (2 levels) in dispatch'
/Users/damuz91/.rvm/gems/ruby-2.7.0/gems/sidekiq-6.3.1/lib/sidekiq/job_retry.rb:79:in `global'
/Users/damuz91/.rvm/gems/ruby-2.7.0/gems/sidekiq-6.3.1/lib/sidekiq/processor.rb:124:in `block in dispatch'
/Users/damuz91/.rvm/gems/ruby-2.7.0/gems/sidekiq-6.3.1/lib/sidekiq/logger.rb:11:in `with'
/Users/damuz91/.rvm/gems/ruby-2.7.0/gems/sidekiq-6.3.1/lib/sidekiq/job_logger.rb:33:in `prepare'
/Users/damuz91/.rvm/gems/ruby-2.7.0/gems/sidekiq-6.3.1/lib/sidekiq/processor.rb:123:in `dispatch'
/Users/damuz91/.rvm/gems/ruby-2.7.0/gems/sidekiq-6.3.1/lib/sidekiq/processor.rb:162:in `process'
/Users/damuz91/.rvm/gems/ruby-2.7.0/gems/sidekiq-6.3.1/lib/sidekiq/processor.rb:78:in `process_one'
/Users/damuz91/.rvm/gems/ruby-2.7.0/gems/sidekiq-6.3.1/lib/sidekiq/processor.rb:68:in `run'
/Users/damuz91/.rvm/gems/ruby-2.7.0/gems/sidekiq-6.3.1/lib/sidekiq/util.rb:43:in `watchdog'
/Users/damuz91/.rvm/gems/ruby-2.7.0/gems/sidekiq-6.3.1/lib/sidekiq/util.rb:52:in `block in safe_thread'
```

My environment:
OSX 12.1
Ruby 2.7 over RVM
Sidekiq 6.3.1
Rails 5.2.6
Using ActiveJob

**Comment by damuz91** [comment]
Sorry my bad.
When i first installed with `gem 'sidekiq-history'` it fetched version 0.0.11, but in version (current) 0.0.12 i see it has the missing code where it makes the gem to work with Sidekiq > v 6.2.
So i had to `gem 'sidekiq-history', '~> 0.0.12'` and it fixed it.
Wonder why the index won't fetch the very last version of the gem. @russ 

And thanks, good job!
